max_width = 120
binop_separator = "Back"
wrap_comments = true
condense_wildcard_suffixes = true
edition = "2021"
enum_discrim_align_threshold = 20
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
space_after_colon = true
struct_field_align_threshold = 20
use_field_init_shorthand = true
use_try_shorthand = true